#!/bin/bash


SOURCE_DIR="$HOME/Data_file/" #what we went's to backup
LOG_FILE="$HOME/backup.log"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
#validation check for SOURCE_DIR

if [ ! -d  "$SOURCE_DIR" ]; then
	echo "Error: Source directory $SOURCE_DIR does't exit!" >> "LOG_FILE"
	exit 1
fi
BACKUP_DIR="$HOME/backup/local" # where we went's to store/backup our data

#validation check for BACKUP_DIR
if [ ! -d "$BACKUP_DIR" ]; then
	echo "Error: backup directory $BACKUP_DIR does't exit!" >> "LOG_FILE"
	echo "Backup directory not found!"
	echo "Creating backup directory in 5 seconds..."

#wait for 5 second creating folder BACKUP_DIR
	for _  in {1..5}; do
	 echo -n "."
	 sleep 1
	done
#now create folder BACKUP_DIR
 	sudo mkdir -p "$BACKUP_DIR"
	sudo chown "$USER":"$USER" "$BACKUP_DIR"
fi
echo "$BACKUP_DIR is successfull"

if [ ! -w "$BACKUP_DIR" ]; then
	    echo "Error: No write permission on $BACKUP_DIR" >> "$LOG_FILE"
	        exit 1
fi

touch "$LOG_FILE" || { echo "Failed to create $LOG_FILE" >> "$LOG_FILE"; exit 1; }
	 echo "backup started at $TIMESTAMP" >> "$LOG_FILE"


Tar_backup() {
	TAR_FILE="$BACKUP_DIR/backup_$TIMESTAMP.tar.gz"
	if tar -czvf "$TAR_FILE" $EXCLUDE "$SOUCRE_DIR" >> "$LOG_FILE" 2>&1; then
		echo "Tar backup successfully: $TAR_FILE" >> "$LOG_FILE"
	else
		echo "Tar backup failed!" >> "$LOG_FILE"
		exit 1
	fi

